### ISSUE TITLE
ttl setting to 0 actually sets the expireTime, cache-manager does this different ?

### ISSUE THREAD

**Issue by iangregsondev** [rolandstarke/node-cache-manager-fs-hash#7]
Hi,

I was checking the json file that was produced as part of this library.

I have set it to 0 (ttl) which in cache-manager is supposed to disable the ttl, i.e. it never expires.

I am doing this 

```
    this.cacheManager = cacheManager.caching({
      store: fsStore,
      ttl: 0, // I am passing ZERO here to never expire.
      options: {
        path: path.join(__dirname, "disk-cache-xp"), //path for cached files
        subdirs: true,
      },
    })
```

If you noticed there is an expiry time

```
{"expireTime":1600433234374,"key":"hello","val":1600429634373}
```

Is this correct ?

This means its going to expire right ?

Thanks in advance

**Comment by rolandstarke** [comment]
Hi,

you are right, as it is right now setting it to 0 will make it expire immediately. Other stores like the build in memory store handle 0 as never expire.

**Comment by rolandstarke** [comment]
What stores should do with a ttl of 0 is not specified by the cache-manager. https://github.com/BryanDonovan/node-cache-manager/issues/43
To make sure it works with every cache store I guess one would need to use some arbitrary large number like 1 year as ttl. 
 `{ttl: 60 * 60 * 24 * 365}`.

**Comment by iangregsondev** [comment]
Hi @rolandstarke not too sure if i understand.

Right now, it doesn't expire, it seems to hold, I am calling it and I am getting back the cached version - when set to "0" ttl.

The problem that I foresee is that the json file that this library stores has a expire value.

Can you confirm ?

Thanks

**Comment by rolandstarke** [comment]
There is a test in this library that tests that setting ttl to 0 will return a cache miss. 
https://github.com/rolandstarke/node-cache-manager-fs-hash/blob/66d8798b1a3131b58fafdd6402fd64d6acaeaca9/test/index.test.js#L157-L162




So right now I would assume it's something else why you get a cached version, maybe because one of those:
- the cache-manager has a feature if you use the `.wrap` method and call the function multiple times before it finishes, it is actually just called once and all calls get the same return value.
- there was a higher ttl before, changing it to 0 afterwards will not expire old keys
- the Multi-Store is used with an other Store Engine that handles 0 as never expire
